"""Shared primitives for evidence-bound equity-research agents.

The agents in this package do not replace the deterministic valuation model.
They inspect structured evidence generated by the existing research workbook,
persist auditable snapshots, and optionally use an LLM for qualitative reasoning.
Any AI narrative is kept separate from source data and calculations.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


@dataclass
class AgentResult:
    name: str
    status: str
    summary: str
    details: dict[str, Any] = field(default_factory=dict)
    artifacts: list[str] = field(default_factory=list)
    ai_narrative: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class AgentContext:
    ticker: str
    repo_root: Path
    workbook_path: Path
    run_dir: Path
    use_ai: bool = False
    ai_model: str | None = None
    shared: dict[str, Any] = field(default_factory=dict)

    @property
    def research_data_dir(self) -> Path:
        path = self.repo_root / "research_data" / self.ticker
        path.mkdir(parents=True, exist_ok=True)
        return path

    def write_json(self, filename: str, payload: Any) -> Path:
        path = self.run_dir / filename
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False, default=str) + "\n", encoding="utf-8")
        return path


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def normalize_json_value(value: Any) -> Any:
    if value is None or isinstance(value, (str, int, float, bool)):
        return value
    if hasattr(value, "isoformat"):
        try:
            return value.isoformat()
        except Exception:
            pass
    return str(value)


def rows_to_dicts(headers: Iterable[Any], rows: Iterable[Iterable[Any]]) -> list[dict[str, Any]]:
    keys = [str(x).strip() if x is not None else "" for x in headers]
    out: list[dict[str, Any]] = []
    for row in rows:
        item = {k: normalize_json_value(v) for k, v in zip(keys, row) if k}
        if any(v not in (None, "") for v in item.values()):
            out.append(item)
    return out


class OpenAIResearchClient:
    """Small opt-in wrapper around the OpenAI Responses API.

    The wrapper is intentionally text-only and evidence-bound. It receives a
    JSON payload that has already been extracted from local research artifacts;
    it does not have browsing or trading tools.
    """

    def __init__(self, model: str | None = None):
        if not os.getenv("OPENAI_API_KEY"):
            raise RuntimeError("OPENAI_API_KEY is required when --ai is enabled.")
        self.model = model or os.getenv("OPENAI_RESEARCH_MODEL") or "gpt-5.5"
        try:
            from openai import OpenAI
        except ImportError:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "openai"])
            from openai import OpenAI
        self._client = OpenAI()

    def analyze(self, agent_name: str, instructions: str, evidence: dict[str, Any]) -> str:
        system = (
            f"You are the {agent_name} inside an equity-research workflow. "
            "Use only the evidence in the input JSON. Never invent current facts, prices, "
            "filing contents, management guidance, or institutional views. Clearly separate "
            "reported facts, calculations, and inference. If evidence is insufficient, say so. "
            "Do not make trades or silently change valuation assumptions. "
            + instructions
        )
        response = self._client.responses.create(
            model=self.model,
            instructions=system,
            input=json.dumps(evidence, ensure_ascii=False, default=str),
        )
        return (response.output_text or "").strip()
